version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/mydb
    command: sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npx prisma db seed &&
      node ./dist/src/index.js"
