version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: test-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"