version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/mydb
    volumes:
      - .:/app
    command: sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npx prisma db seed &&
      node dist/index.js"
